/**
 * C++ generator.
 *
 * Conventions (from generator-conventions.md):
 *   - EnumType → enum class with wire-value comments
 *   - ObjectType → struct with members
 *   - Method(call) → free function returning FireboltResult<T>
 *   - Optional params → std::optional<T>
 *   - Method(subscribe) → using UnsubscribeFn + callback
 *   - Output: generated/cpp/firebolt/<Module>.hpp
 */

import {
  ArrayRef,
  EnumTypeDecl,
  Method,
  Module,
  NamedRef,
  ObjectTypeDecl,
  OptionalRef,
  Param,
  PrimitiveRef,
  TypeDecl,
  TypeRef,
} from "../ast/types";
import { GenConfig, GeneratorOutput, extractConstraints, formatConstraintNote, registerGenerator } from "./index";

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

function generate(module: Module, _config: GenConfig): GeneratorOutput[] {
  const guard = `FIREBOLT_${module.name.toUpperCase()}_HPP`;
  const lines: string[] = [];

  lines.push(`// Auto-generated by firebolt-gen — do not edit manually.`);
  lines.push(`#pragma once`);
  lines.push(`#ifndef ${guard}`);
  lines.push(`#define ${guard}`);
  lines.push(``);
  lines.push(`#include <functional>`);
  lines.push(`#include <optional>`);
  lines.push(`#include <string>`);
  lines.push(`#include "firebolt/result.hpp"`);
  lines.push(``);
  lines.push(`namespace firebolt {`);
  lines.push(`namespace ${module.name.toLowerCase()} {`);
  lines.push(``);

  for (const decl of module.types) {
    lines.push(...emitTypeDecl(decl));
    lines.push(``);
  }

  // using UnsubscribeFn for subscribe methods
  const hasSub = module.methods.some((m) => m.kind === "subscribe");
  if (hasSub) {
    lines.push(`using UnsubscribeFn = std::function<void()>;`);
    lines.push(``);
  }

  for (const method of module.methods) {
    lines.push(...emitMethod(method, module.name));
    lines.push(``);
  }

  lines.push(`} // namespace ${module.name.toLowerCase()}`);
  lines.push(`} // namespace firebolt`);
  lines.push(``);
  lines.push(`#endif // ${guard}`);
  lines.push(``);

  return [
    {
      filePath: `cpp/firebolt/${module.name}.hpp`,
      content: lines.join("\n"),
    },
  ];
}

// ---------------------------------------------------------------------------
// Type declarations
// ---------------------------------------------------------------------------

function emitTypeDecl(decl: TypeDecl): string[] {
  if (decl.kind === "enum") return emitEnum(decl);
  if (decl.kind === "object") return emitObject(decl);
  return [`// [unsupported TypeDecl kind: ${(decl as TypeDecl).kind}]`];
}

function emitEnum(decl: EnumTypeDecl): string[] {
  const lines: string[] = [];
  lines.push(`enum class ${decl.name} {`);
  for (const v of decl.values) {
    lines.push(`    ${v.identifier}, // wire: "${v.serializedId}"`);
  }
  lines.push(`};`);
  return lines;
}

function emitObject(decl: ObjectTypeDecl): string[] {
  const lines: string[] = [];
  lines.push(`struct ${decl.name} {`);
  for (const prop of decl.properties) {
    const isOpt = !prop.required;
    const ref =
      isOpt && prop.type.kind === "optional"
        ? (prop.type as OptionalRef).inner
        : prop.type;
    const cppType = isOpt
      ? `std::optional<${typeRefToCpp(ref)}>`
      : typeRefToCpp(ref);
    const c = extractConstraints(ref);
    const note = c ? ` // ${formatConstraintNote(c)}` : "";
    lines.push(`    ${cppType} ${prop.name};${note}`);
  }
  lines.push(`};`);
  return lines;
}

// ---------------------------------------------------------------------------
// Methods
// ---------------------------------------------------------------------------

function emitMethod(method: Method, _moduleName: string): string[] {
  if (method.kind === "call") return emitCallMethod(method);
  return emitSubscribeMethod(method);
}

function emitCallMethod(method: Method): string[] {
  const params = method.params.map(paramToCpp).join(", ");
  const resultType =
    method.result === null ? "FireboltResult<void>" : `FireboltResult<${typeRefToCpp(method.result)}>`;
  const lines: string[] = [];
  const constraintNote = buildConstraintNote(method);
  if (constraintNote) lines.push(`// ${constraintNote}`);
  lines.push(`${resultType} ${method.name}(${params});`);
  return lines;
}

function emitSubscribeMethod(method: Method): string[] {
  const params = method.params.map(paramToCpp);
  const callbackType =
    method.result === null
      ? `std::function<void()>`
      : `std::function<void(${typeRefToCpp(method.result)})>`;
  params.push(`${callbackType} callback`);
  const lines: string[] = [];
  const constraintNote = buildConstraintNote(method);
  if (constraintNote) lines.push(`// ${constraintNote}`);
  lines.push(`UnsubscribeFn ${method.name}(${params.join(", ")});`);
  return lines;
}

function buildConstraintNote(method: Method): string {
  const notes: string[] = [];
  for (const p of method.params) {
    const c = extractConstraints(p.type);
    if (c) notes.push(`${p.name}: ${formatConstraintNote(c)}`);
  }
  if (method.result) {
    const c = extractConstraints(method.result);
    if (c) notes.push(`result: ${formatConstraintNote(c)}`);
  }
  return notes.length ? `Constraints — ${notes.join(" | ")}` : "";
}

function paramToCpp(p: Param): string {
  if (p.type.kind === "optional") {
    return `std::optional<${typeRefToCpp((p.type as OptionalRef).inner)}> ${p.name} = std::nullopt`;
  }
  return `${typeRefToCpp(p.type)} ${p.name}`;
}

// ---------------------------------------------------------------------------
// TypeRef → C++ string
// ---------------------------------------------------------------------------

function typeRefToCpp(ref: TypeRef): string {
  switch (ref.kind) {
    case "primitive":
      return primitiveToCpp(ref as PrimitiveRef);
    case "named": {
      const nr = ref as NamedRef;
      return nr.module
        ? `firebolt::${nr.module.toLowerCase()}::${nr.name}`
        : nr.name;
    }
    case "array":
      return `std::vector<${typeRefToCpp((ref as ArrayRef).items)}>`;
    case "optional":
      return `std::optional<${typeRefToCpp((ref as OptionalRef).inner)}>`;
  }
}

function primitiveToCpp(ref: PrimitiveRef): string {
  switch (ref.primitive) {
    case "bool":
      return "bool";
    case "string":
      return "std::string";
    case "unsigned":
      return "int32_t";
    case "double":
      return "double";
  }
}

// ---------------------------------------------------------------------------
// Register
// ---------------------------------------------------------------------------

registerGenerator("cpp", generate, "native");
