/**
 * Tests for the inject-js-types generator output.
 *
 * Tests that the generator produces a single TypeScript definition file
 * matching the inject-js factory/builder pattern.
 */

import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import {
  GenConfig,
  runAllFullAST,
} from "./index";
import { Module, CanonicalAST } from "../ast/types";

// Register the generator module for side-effects (registers itself)
import "./inject-js-types";

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

/** Build a minimal CanonicalAST with one web module that has a call and a subscribe */
function makeAST(extra: Partial<CanonicalAST> = {}): CanonicalAST {
  const localeModule: Module = {
    name: "Localization",
    platform: "web",
    types: [
      {
        kind: "enum",
        name: "Language",
        values: [
          { identifier: "En", serializedId: "en", description: "" },
          { identifier: "Fr", serializedId: "fr", description: "" },
        ],
        description: "Language enum",
      },
    ],
    methods: [
      {
        kind: "call",
        name: "country",
        params: [],
        result: { kind: "primitive", primitive: "string" },
        description: "Returns the country code",
      },
      {
        kind: "subscribe",
        name: "onCountryChanged",
        params: [],
        result: { kind: "primitive", primitive: "string" },
        description: "Fired when the country changes",
      },
    ],
  };

  return {
    version: "9.0",
    modules: [localeModule],
    ...extra,
  };
}

/** Generate the definition file for a given AST */
function generateDefinitions(ast: CanonicalAST): string {
  const config: GenConfig = { outDir: "/tmp/test" };
  const outputs = runAllFullAST(ast, config, ["inject-js-types"]);
  return outputs[0].content;
}

// ---------------------------------------------------------------------------
// Generator output tests
// ---------------------------------------------------------------------------

describe("inject-js-types generator", () => {
  test("generator is registered", () => {
    const config: GenConfig = { outDir: "/tmp/test" };
    expect(() => {
      runAllFullAST(makeAST(), config, ["inject-js-types"]);
    }).not.toThrow();
  });

  test("produces single output file", () => {
    const outputs = runAllFullAST(makeAST(), { outDir: "/tmp/test" }, ["inject-js-types"]);
    expect(outputs).toHaveLength(1);
    expect(outputs[0].filePath).toBe("inject-js/firebolt-inject.d.ts");
  });
});

describe("2.2 Single file output generation", () => {
  test("output file contains TypeScript definitions", () => {
    const content = generateDefinitions(makeAST());
    expect(content).toContain("interface FireboltTransport");
    expect(content).toContain("interface FireboltClient");
    expect(content).toContain("declare function factory");
  });

  test("output file has correct header", () => {
    const content = generateDefinitions(makeAST());
    expect(content).toContain("// Auto-generated by firebolt-gen");
    expect(content).toContain("TypeScript definitions for inject-js factory/builder pattern");
  });
});

describe("2.3 Platform filtering", () => {
  test("web platform module is included", () => {
    const webModule: Module = {
      name: "WebModule",
      platform: "web",
      types: [],
      methods: [
        {
          kind: "call",
          name: "test",
          params: [],
          result: { kind: "primitive", primitive: "string" },
          description: "Test method",
        },
      ],
    };
    const ast = makeAST();
    ast.modules.push(webModule);

    const content = generateDefinitions(ast);
    expect(content).toContain("WebModule");
  });

  test("both platform module is included", () => {
    const bothModule: Module = {
      name: "BothModule",
      platform: "both",
      types: [],
      methods: [
        {
          kind: "call",
          name: "test",
          params: [],
          result: { kind: "primitive", primitive: "string" },
          description: "Test method",
        },
      ],
    };
    const ast = makeAST();
    ast.modules.push(bothModule);

    const content = generateDefinitions(ast);
    expect(content).toContain("BothModule");
  });

  test("native platform module is excluded", () => {
    const nativeModule: Module = {
      name: "NativeModule",
      platform: "native",
      types: [],
      methods: [
        {
          kind: "call",
          name: "test",
          params: [],
          result: { kind: "primitive", primitive: "string" },
          description: "Test method",
        },
      ],
    };
    const ast = makeAST();
    ast.modules.push(nativeModule);

    const content = generateDefinitions(ast);
    expect(content).not.toContain("NativeModule");
  });
});

describe("2.4 Transport interface structure", () => {
  test("FireboltTransport has required methods", () => {
    const content = generateDefinitions(makeAST());
    expect(content).toContain("send(data: string): void");
    expect(content).toContain("open(): void");
    expect(content).toContain("close(): void");
  });

  test("FireboltTransport has optional callbacks", () => {
    const content = generateDefinitions(makeAST());
    expect(content).toContain("onMessage?: (raw: string) => void");
    expect(content).toContain("onOpen?: () => void");
    expect(content).toContain("onClose?: () => void");
    expect(content).toContain("onError?: (error: unknown) => void");
  });
});

describe("2.5 Extension schema interface structure", () => {
  test("ExtensionSchema has required name", () => {
    const content = generateDefinitions(makeAST());
    expect(content).toMatch(/name:\s*string/);
  });

  test("ExtensionSchema has optional method arrays", () => {
    const content = generateDefinitions(makeAST());
    expect(content).toContain("methods?: string[]");
    expect(content).toContain("events?: string[]");
    expect(content).toContain("methodsWithObject?: string[]");
  });
});

describe("2.6 Factory configuration interface structure", () => {
  test("FactoryConfig has required transport", () => {
    const content = generateDefinitions(makeAST());
    expect(content).toContain("transport: FireboltTransport");
  });

  test("FactoryConfig has optional extension schema", () => {
    const content = generateDefinitions(makeAST());
    expect(content).toContain("extensionSchema?: string | ExtensionSchema[]");
  });

  test("FactoryConfig has optional debug flag", () => {
    const content = generateDefinitions(makeAST());
    expect(content).toContain("enableDebug?: boolean");
  });
});

describe("2.7 FireboltClient interface with all modules", () => {
  test("FireboltClient includes web/both modules", () => {
    const content = generateDefinitions(makeAST());
    expect(content).toContain("Localization: typeof Localization");
  });

  test("FireboltClient includes cleanup method", () => {
    const content = generateDefinitions(makeAST());
    expect(content).toContain("cleanup(): void");
  });
});

describe("2.8 Export statements presence", () => {
  test("exports factory function", () => {
    const content = generateDefinitions(makeAST());
    expect(content).toContain("export { factory");
  });

  test("exports all public types", () => {
    const content = generateDefinitions(makeAST());
    expect(content).toContain("FireboltClient");
    expect(content).toContain("FireboltTransport");
    expect(content).toContain("FactoryConfig");
    expect(content).toContain("ExtensionSchema");
  });
});

describe("2.9 TypeScript compilation test", () => {
  let outDir: string;

  beforeAll(() => {
    outDir = fs.mkdtempSync(path.join(os.tmpdir(), "firebolt-types-test-"));
  });

  afterAll(() => {
    fs.rmSync(outDir, { recursive: true, force: true });
  });

  test("generated .d.ts file compiles without errors", () => {
    const content = generateDefinitions(makeAST());
    const destPath = path.join(outDir, "firebolt-inject.d.ts");
    fs.writeFileSync(destPath, content, "utf8");

    // Try to compile with TypeScript
    const result = require("child_process").spawnSync(
      "npx",
      ["tsc", "--noEmit", "--strict", destPath],
      { encoding: "utf8" }
    );

    // TypeScript compiler returns 0 on success
    expect(result.status).toBe(0);
  });
});