/**
 * inject-js-types TypeScript definition generator.
 *
 * Emits a single TypeScript definition file (firebolt-inject.d.ts) that matches
 * the inject-js factory/builder pattern, enabling VS Code intellisense and API
 * documentation for app developers.
 *
 * Only web-platform modules (platform: "web" | "both") are included.
 */

import {
  CanonicalAST,
  Module,
  TypeDecl,
  Method,
  Param,
  TypeRef,
  OptionalRef,
  PrimitiveRef,
  NamedRef,
  ArrayRef,
  ObjectTypeDecl,
} from "../ast/types";
import { GenConfig, GeneratorOutput, registerFullASTGenerator, extractConstraints, formatConstraintNote } from "./index";
import { loadAllSpecs, SpecModuleData, findMethodSpec } from "./spec-reader";

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

function generate(ast: CanonicalAST, _config: GenConfig): GeneratorOutput[] {
  const lines: string[] = [];

  // Load spec data for enhanced JSDoc generation
  const specData = loadAllSpecs();

  lines.push(`// Auto-generated by firebolt-gen — do not edit manually.`);
  lines.push(`// TypeScript definitions for FireboltServiceManager global pattern`);
  lines.push(``);

  // Filter to web + both platform modules only
  const webModules = ast.modules.filter(
    (m) => m.platform === "web" || m.platform === "both"
  );

  // Emit module namespaces
  for (const mod of webModules) {
    const moduleSpec = specData.get(mod.name);
    lines.push(...emitModuleNamespace(mod, ast, moduleSpec));
    lines.push(``);
  }

  // Emit module interfaces
  for (const mod of webModules) {
    const moduleSpec = specData.get(mod.name);
    lines.push(...emitModuleInterface(mod, moduleSpec));
    lines.push(``);
  }

  // Emit FireboltClient interface
  lines.push(...emitFireboltClientInterface(webModules));
  lines.push(``);

  // Emit FireboltServiceManager interface
  lines.push(...emitFireboltServiceManagerInterface());
  lines.push(``);

  // Emit global FireboltServiceManager declaration
  lines.push(...emitFireboltServiceManagerGlobal());
  lines.push(``);

  // Emit export statements
  lines.push(...emitExportStatements());
  lines.push(``);
  lines.push(`// Export Firebolt namespace for direct consumption`);
  lines.push(`export as namespace Firebolt;`);

  return [
    {
      filePath: "inject-js/firebolt-inject.d.ts",
      content: lines.join("\n"),
    },
  ];
}

// ---------------------------------------------------------------------------
// Core interface generation
// ---------------------------------------------------------------------------

function emitFireboltServiceManagerInterface(): string[] {
  return [
    `/** FireboltServiceManager global interface injected by WPE WebKit extension */`,
    `interface FireboltServiceManager {`,
    `  /** Version of the Firebolt SDK */`,
    `  readonly version: string;`,
    `  /** Get the Firebolt client instance */`,
    `  get(): Promise<FireboltClient>;`,
    `}`,
  ];
}

function emitFireboltClientInterface(modules: Module[]): string[] {
  const lines: string[] = [
    `/** Firebolt client with all module namespaces */`,
    `interface FireboltClient {`,
  ];

  for (const mod of modules) {
    lines.push(`  ${mod.name}: Firebolt.${mod.name}Module;`);
  }

  lines.push(`  /** Cleanup and close connection */`);
  lines.push(`  cleanup(): void;`);
  lines.push(`}`);

  return lines;
}

function emitFireboltServiceManagerGlobal(): string[] {
  return [
    `/** Global FireboltServiceManager injected by WPE WebKit extension */`,
    `declare global { const FireboltServiceManager: FireboltServiceManager; }`,
  ];
}

function emitExportStatements(): string[] {
  return [
    `export { FireboltClient };`,
  ];
}

// ---------------------------------------------------------------------------
// Module namespace generation
// ---------------------------------------------------------------------------

function emitModuleNamespace(module: Module, ast: CanonicalAST, moduleSpec?: SpecModuleData): string[] {
  const lines: string[] = [
    `declare namespace Firebolt {`,
    `  namespace ${module.name} {`,
  ];

  // Emit type declarations (enums, interfaces)
  for (const decl of module.types) {
    const typeLines = emitTypeDecl(decl);
    for (const line of typeLines) {
      lines.push(`    ${line}`);
    }
    lines.push(``);
  }

  // Emit parameter interfaces for methods with parameters
  for (const method of module.methods) {
    // Skip native-only methods when generating for web
    if (method.platform === "native") continue;

    if (method.kind === "call" && method.params.length > 0) {
      const paramInterface = emitParamInterface(method);
      if (paramInterface.length > 0) {
        for (const line of paramInterface) {
          lines.push(`    ${line}`);
        }
        lines.push(``);
      }
    }
  }

  // Emit method signatures
  for (const method of module.methods) {
    // Skip native-only methods when generating for web
    if (method.platform === "native") continue;

    const methodLines = emitMethod(method, module.name, ast, moduleSpec);
    for (const line of methodLines) {
      lines.push(`    ${line}`);
    }
    lines.push(``);
  }

  lines.push(`  }`);
  lines.push(`}`);

  return lines;
}

// ---------------------------------------------------------------------------
// Helper functions (adapted from typescript.ts)
// ---------------------------------------------------------------------------

function isPrimitiveWrapPattern(method: Method, moduleName: string, ast: CanonicalAST): boolean {
  if (method.params.length !== 1) {
    return false;
  }
  const param = method.params[0];
  if (param.type.kind !== "named") {
    return false;
  }

  const namedRef = param.type as NamedRef;

  // Find the module in the AST
  const module = ast.modules.find(m => m.name === moduleName);
  if (!module) {
    return false;
  }

  // Find the type declaration
  const typeDecl = module.types.find(t => t.name === namedRef.name);
  if (!typeDecl || typeDecl.kind !== "object") {
    return false;
  }

  // Check for single primitive property
  if (typeDecl.properties.length !== 1) {
    return false;
  }

  const prop = typeDecl.properties[0];
  if (!prop.required || prop.type.kind !== "primitive") {
    return false;
  }

  return true;
}

function findTypeDeclInModule(method: Method, moduleName: string, ast: CanonicalAST): TypeDecl | null {
  const module = ast.modules.find(m => m.name === moduleName);
  if (!module) {
    return null;
  }

  const param = method.params[0];
  if (param.type.kind !== "named") {
    return null;
  }

  const namedRef = param.type as NamedRef;
  return module.types.find(t => t.name === namedRef.name) || null;
}

function getParamInterfaceName(method: Method): string {
  // Capitalize first letter of method name
  const capitalizedMethod = method.name.charAt(0).toUpperCase() + method.name.slice(1);
  return `${capitalizedMethod}Params`;
}

function emitParamInterface(method: Method): string[] {
  if (method.params.length === 0) {
    return [];
  }

  const interfaceName = getParamInterfaceName(method);
  const lines: string[] = [];

  lines.push(`/** Parameters for ${method.name} */`);
  lines.push(`interface ${interfaceName} {`);

  for (const param of method.params) {
    const isOptional = param.type.kind === "optional";
    const opt = isOptional ? "?" : "";
    const ref = isOptional
      ? (param.type as OptionalRef).inner
      : param.type;
    const inner = typeRefToTS(ref);
    const c = extractConstraints(ref);
    if (c) lines.push(`  /** Constraints: ${formatConstraintNote(c)} */`);
    lines.push(`  ${param.name}${opt}: ${inner};`);
  }

  lines.push(`}`);
  return lines;
}


function emitTypeDecl(decl: TypeDecl): string[] {
  if (decl.kind === "enum") {
    return emitEnum(decl);
  }
  if (decl.kind === "object") {
    return emitObject(decl);
  }
  return [`// [unsupported TypeDecl kind: ${decl.kind}]`];
}

function emitEnum(decl: TypeDecl): string[] {
  const literals = (decl as any).values.map((v: any) => `"${v.serializedId}"`).join(" | ");
  const lines: string[] = [];
  if (decl.description) {
    lines.push(`/** ${decl.description} */`);
  }
  lines.push(`type ${decl.name} = ${literals};`);
  return lines;
}

function emitObject(decl: ObjectTypeDecl): string[] {
  const lines: string[] = [];
  if (decl.description) {
    lines.push(`/** ${decl.description} */`);
  }
  lines.push(`interface ${decl.name} {`);
  for (const prop of decl.properties) {
    const opt = !prop.required ? "?" : "";
    const ref =
      !prop.required && prop.type.kind === "optional"
        ? (prop.type as OptionalRef).inner
        : prop.type;
    const inner = typeRefToTS(ref);
    const c = extractConstraints(ref);
    if (c) lines.push(`  /** Constraints: ${formatConstraintNote(c)} */`);
    lines.push(`  ${prop.name}${opt}: ${inner};`);
  }
  lines.push(`}`);
  return lines;
}

// ---------------------------------------------------------------------------
// Module interface generation (NEW)
// ---------------------------------------------------------------------------

function emitModuleInterface(module: Module, moduleSpec?: SpecModuleData): string[] {
  const lines: string[] = [
    `declare namespace Firebolt {`,
  ];

  // Add module-level JSDoc
  if (moduleSpec) {
    lines.push(`  /**`);
    lines.push(`   * ${moduleSpec.description}`);
    if (moduleSpec.platform) {
      lines.push(`   * @platform ${moduleSpec.platform}`);
    }
    if (moduleSpec.version) {
      lines.push(`   * @since ${moduleSpec.version}`);
    }
    if (moduleSpec.stability) {
      lines.push(`   * @stability ${moduleSpec.stability}`);
    }
    lines.push(`   */`);
  }

  lines.push(`  interface ${module.name}Module {`);

  // Emit method signatures for module interface
  for (const method of module.methods) {
    // Skip native-only methods when generating for web
    if (method.platform === "native") continue;

    const methodLines = emitMethodSignature(method, module.name, moduleSpec);
    for (const line of methodLines) {
      lines.push(`    ${line}`);
    }
    lines.push(``);
  }

  lines.push(`  }`);
  lines.push(`}`);

  return lines;
}

function emitMethodSignature(method: Method, moduleName: string, moduleSpec?: SpecModuleData): string[] {
  if (method.kind === "call") {
    return emitCallMethodSignature(method, moduleName, moduleSpec);
  }
  return emitSubscribeMethodSignature(method, moduleName, moduleSpec);
}

function emitCallMethodSignature(method: Method, moduleName: string, moduleSpec?: SpecModuleData): string[] {
  const methodSpec = moduleSpec ? findMethodSpec(moduleSpec, method.name, "call") : undefined;
  
  let paramStr: string;
  if (method.params.length === 0) {
    paramStr = "";
  } else {
    const interfaceName = getParamInterfaceName(method);
    paramStr = `params: ${moduleName}.${interfaceName}`;
  }

  const resultType = method.result === null ? "void" : typeRefToTS(method.result);
  
  // Build enhanced JSDoc
  let doc = `/** ${method.description}`;
  
  // Add @since if available
  if (methodSpec?.since) {
    doc += `\n   * @since ${methodSpec.since}`;
  }
  
  // Add @platform
  const platform = method.platform || (moduleSpec?.platform);
  if (platform) {
    doc += `\n   * @platform ${platform}`;
  }
  
  // Add @param descriptions
  for (const param of method.params) {
    const paramSpec = methodSpec?.params?.find(p => p.name === param.name);
    const desc = paramSpec?.description || param.description;
    const opt = param.type.kind === "optional" ? "?" : "";
    doc += `\n   * @param ${param.name}${opt} - ${desc}`;
  }
  
  // Add @returns with description
  if (method.result) {
    const resultDesc = methodSpec?.result?.description || typeRefToTS(method.result);
    doc += `\n   * @returns Promise<${typeRefToTS(method.result)}> - ${resultDesc}`;
  } else {
    doc += `\n   * @returns Promise<void>`;
  }
  
  // Add examples from spec
  if (methodSpec?.examples && methodSpec.examples.length > 0) {
    for (const example of methodSpec.examples) {
      doc += `\n   * @example`;
      doc += `\n   * ${example.description}`;
      const exampleCode = formatExampleCode(example, moduleName, method.name, method.params);
      for (const line of exampleCode) {
        doc += `\n   *   ${line}`;
      }
    }
  }
  
  doc += ` */`;

  return [doc, `${method.name}(${paramStr}): Promise<${resultType}>;`];
}

function emitSubscribeMethodSignature(method: Method, moduleName: string, moduleSpec?: SpecModuleData): string[] {
  const methodSpec = moduleSpec ? findMethodSpec(moduleSpec, method.name, "subscribe") : undefined;
  
  const callbackType = method.result === null 
    ? "(event: null, cancelled: boolean) => void" 
    : `(event: ${typeRefToTS(method.result)}, cancelled: boolean) => void`;
  const paramStr = method.params.map(paramToTS).join(", ");
  const sep = paramStr ? ", " : "";
  
  // Build enhanced JSDoc
  let doc = `/** ${method.description}`;
  
  // Add @since if available
  if (methodSpec?.since) {
    doc += `\n   * @since ${methodSpec.since}`;
  }
  
  // Add @platform
  const platform = method.platform || (moduleSpec?.platform);
  if (platform) {
    doc += `\n   * @platform ${platform}`;
  }
  
  // Add @param for callback
  doc += `\n   * @param callback - Event callback function`;
  
  // Add @returns
  doc += `\n   * @returns Unsubscribe function`;
  
  // Add examples from spec
  if (methodSpec?.examples && methodSpec.examples.length > 0) {
    for (const example of methodSpec.examples) {
      doc += `\n   * @example`;
      doc += `\n   * ${example.description}`;
      const exampleCode = formatSubscribeExampleCode(example, moduleName, method.name, method.params);
      for (const line of exampleCode) {
        doc += `\n   *   ${line}`;
      }
    }
  }
  
  doc += ` */`;

  return [doc, `${method.name}(${paramStr}${sep}callback: ${callbackType}): () => void;`];
}

function formatExampleCode(example: any, moduleName: string, methodName: string, params: Param[]): string[] {
  const lines: string[] = [];
  
  if (params.length === 0) {
    // No parameters - direct call
    lines.push(`const result = await firebolt.${moduleName}.${methodName}();`);
  } else {
    // With parameters - show parameter construction
    lines.push(`const params = {`);
    if (example.params) {
      for (const [key, value] of Object.entries(example.params)) {
        const formattedValue = formatValue(value);
        lines.push(`  ${key}: ${formattedValue},`);
      }
    } else {
      // Fallback: generate basic parameter structure
      for (const param of params) {
        if (param.type.kind === "optional") continue;
        lines.push(`  ${param.name}: <${typeRefToTS(param.type)}>,`);
      }
    }
    lines.push(`};`);
    lines.push(`const result = await firebolt.${moduleName}.${methodName}(params);`);
  }
  
  return lines;
}

function formatSubscribeExampleCode(_example: any, moduleName: string, methodName: string, params: Param[]): string[] {
  const lines: string[] = [];
  
  const paramStr = params.map(p => p.name).join(", ");
  const sep = paramStr ? ", " : "";
  
  lines.push(`const unsubscribe = firebolt.${moduleName}.${methodName}(${paramStr}${sep}(event, cancelled) => {`);
  lines.push(`  if (cancelled) {`);
  lines.push(`    console.log('Event was cancelled');`);
  lines.push(`    return;`);
  lines.push(`  }`);
  lines.push(`  console.log('Event:', event);`);
  lines.push(`});`);
  
  return lines;
}

function formatValue(value: unknown): string {
  if (typeof value === "string") {
    return `"${value}"`;
  } else if (typeof value === "number") {
    return String(value);
  } else if (typeof value === "boolean") {
    return String(value);
  } else if (value === null) {
    return "null";
  } else if (typeof value === "object") {
    return JSON.stringify(value);
  }
  return String(value);
}

function emitMethod(method: Method, moduleName: string, ast: CanonicalAST, moduleSpec?: SpecModuleData): string[] {
  if (method.kind === "call") {
    return emitCallMethod(method, moduleName, ast, moduleSpec);
  }
  return emitSubscribeMethod(method, moduleName, moduleSpec);
}

function emitCallMethod(method: Method, moduleName: string, ast: CanonicalAST, moduleSpec?: SpecModuleData): string[] {
  let paramStr: string;

  if (method.params.length === 0) {
    // No parameters
    paramStr = "";
  } else if (isPrimitiveWrapPattern(method, moduleName, ast)) {
    // Primitive-wrap pattern: accept primitive directly
    const param = method.params[0];
    if (param.type.kind === "named") {
      const typeDecl = findTypeDeclInModule(method, moduleName, ast);
      if (typeDecl && typeDecl.kind === "object" && typeDecl.properties.length === 1) {
        const prop = typeDecl.properties[0];
        const primitiveType = typeRefToTS(prop.type);
        paramStr = `value: ${primitiveType}`;
      } else {
        // Fallback to interface
        const interfaceName = getParamInterfaceName(method);
        paramStr = `params: ${interfaceName}`;
      }
    } else {
      // Fallback to interface
      const interfaceName = getParamInterfaceName(method);
      paramStr = `params: ${interfaceName}`;
    }
  } else {
    // All methods with parameters use parameter interface
    const interfaceName = getParamInterfaceName(method);
    paramStr = `params: ${interfaceName}`;
  }

  const resultType =
    method.result === null ? "void" : typeRefToTS(method.result);
  const constraintLines = collectConstraintLines(method);
  const methodSpec = moduleSpec ? findMethodSpec(moduleSpec, method.name, "call") : undefined;
  const exampleLines = methodSpec?.examples && methodSpec.examples.length > 0 
    ? methodSpec.examples.flatMap(ex => formatExampleCode(ex, moduleName, method.name, method.params))
    : emitExample(method, moduleName, ast);

  let doc = `/** ${method.description}`;
  
  // Add @since if available from spec
  if (methodSpec?.since) {
    doc += `\n   * @since ${methodSpec.since}`;
  }
  
  // Add @platform
  const platform = method.platform || (moduleSpec?.platform);
  if (platform) {
    doc += `\n   * @platform ${platform}`;
  }
  
  // Add @param descriptions from spec
  for (const param of method.params) {
    const paramSpec = methodSpec?.params?.find(p => p.name === param.name);
    const desc = paramSpec?.description || param.description;
    const opt = param.type.kind === "optional" ? "?" : "";
    doc += `\n   * @param ${param.name}${opt} - ${desc}`;
  }
  
  if (constraintLines.length) {
    doc += `\n   * Constraints: ${constraintLines.join(" | ")}`;
  }
  
  // Add @returns with description
  if (method.result) {
    const resultDesc = methodSpec?.result?.description || typeRefToTS(method.result);
    doc += `\n   * @returns Promise<${typeRefToTS(method.result)}> - ${resultDesc}`;
  } else {
    doc += `\n   * @returns Promise<void>`;
  }
  
  if (exampleLines.length) {
    doc += `\n   * @example`;
    for (const line of exampleLines) {
      doc += `\n   *   ${line}`;
    }
  }
  doc += ` */`;

  return [
    doc,
    `function ${method.name}(${paramStr}): Promise<${resultType}>;`,
  ];
}

function emitSubscribeMethod(method: Method, moduleName: string, moduleSpec?: SpecModuleData): string[] {
  const callbackType =
    method.result === null ? "(event: null, cancelled: boolean) => void" : `(event: ${typeRefToTS(method.result)}, cancelled: boolean) => void`;
  const paramStr = method.params.map(paramToTS).join(", ");
  const sep = paramStr ? ", " : "";
  const constraintLines = collectConstraintLines(method);
  const methodSpec = moduleSpec ? findMethodSpec(moduleSpec, method.name, "subscribe") : undefined;
  
  let doc = `/** ${method.description}`;
  
  // Add @since if available from spec
  if (methodSpec?.since) {
    doc += `\n   * @since ${methodSpec.since}`;
  }
  
  // Add @platform
  const platform = method.platform || (moduleSpec?.platform);
  if (platform) {
    doc += `\n   * @platform ${platform}`;
  }
  
  // Add @param for callback
  doc += `\n   * @param callback - Event callback function`;
  
  if (constraintLines.length) {
    doc += `\n   * Constraints — event payload: ${constraintLines.join(" | ")}`;
  }
  
  // Add @returns
  doc += `\n   * @returns Unsubscribe function`;
  
  // Add examples from spec
  if (methodSpec?.examples && methodSpec.examples.length > 0) {
    for (const example of methodSpec.examples) {
      doc += `\n   * @example`;
      doc += `\n   * ${example.description}`;
      const exampleCode = formatSubscribeExampleCode(example, moduleName, method.name, method.params);
      for (const line of exampleCode) {
        doc += `\n   *   ${line}`;
      }
    }
  }
  
  doc += ` */`;
  
  return [
    doc,
    `function ${method.name}(${paramStr}${sep}callback: ${callbackType}): () => void;`,
  ];
}

function collectConstraintLines(method: Method): string[] {
  const notes: string[] = [];
  for (const p of method.params) {
    const c = extractConstraints(p.type);
    if (c) notes.push(`${p.name}: ${formatConstraintNote(c)}`);
  }
  if (method.result) {
    const c = extractConstraints(method.result);
    if (c) notes.push(formatConstraintNote(c));
  }
  return notes;
}

function paramToTS(p: Param): string {
  if (p.type.kind === "optional") {
    return `${p.name}?: ${typeRefToTS((p.type as OptionalRef).inner)}`;
  }
  return `${p.name}: ${typeRefToTS(p.type)}`;
}

function emitExample(method: Method, moduleName: string, ast: CanonicalAST): string[] {
  if (method.params.length === 0) {
    return [];
  }

  const lines: string[] = [];

  // Check if this is a primitive-wrap pattern
  if (isPrimitiveWrapPattern(method, moduleName, ast)) {
    const typeDecl = findTypeDeclInModule(method, moduleName, ast);
    if (typeDecl && typeDecl.kind === "object" && typeDecl.properties.length === 1) {
      const prop = typeDecl.properties[0];
      const exampleValue = generateExampleValueForType(prop.type);
      lines.push(`Firebolt.${moduleName}.${method.name}(${exampleValue});`);
      return lines;
    }
  }

  const interfaceName = getParamInterfaceName(method);

  // Generate example values for each parameter
  const exampleParams: string[] = [];
  for (const param of method.params) {
    const isOptional = param.type.kind === "optional";
    // Skip optional parameters in examples to keep them clean
    if (isOptional) continue;

    const exampleValue = generateExampleValue(param);
    exampleParams.push(`  ${param.name}: ${exampleValue}`);
  }

  lines.push(`const params: Firebolt.${moduleName}.${interfaceName} = {`);
  lines.push(...exampleParams);
  lines.push(`};`);
  lines.push(`Firebolt.${moduleName}.${method.name}(params);`);

  return lines;
}

function generateExampleValue(param: Param): string {
  const type = param.type;
  const paramName = param.name.toLowerCase();
  
  if (type.kind === "primitive") {
    const primitive = type as PrimitiveRef;
    switch (primitive.primitive) {
      case "string":
        // Generate more realistic example values based on parameter name
        if (paramName.includes("intent")) return `'{"action":"play","entityId":"entity-123"}'`;
        if (paramName.includes("appid")) return `"app123"`;
        if (paramName.includes("entity")) return `"entity-123"`;
        if (paramName.includes("page")) return `"details"`;
        if (paramName.includes("error")) return `"network"`;
        if (paramName.includes("message")) return `"Connection failed"`;
        if (paramName.includes("event")) return `"user_action"`;
        if (paramName.includes("data")) return `'{"action":"favorite"}'`;
        if (paramName.includes("name")) return `"My Device"`;
        if (paramName.includes("id")) return `"12345"`;
        if (paramName.includes("date") || paramName.includes("time")) return `"2026-09-16T05:43:00.000Z"`;
        if (paramName.includes("watchedon")) return `"2026-09-16T05:43:00.000Z"`;
        return `"${param.name}"`;
      case "bool":
        return "true";
      case "unsigned":
      case "double":
        // Generate more realistic numeric examples
        if (paramName.includes("progress")) return "0.75";
        if (paramName.includes("id")) return "1";
        return "0";
    }
  } else if (type.kind === "optional") {
    const inner = (type as OptionalRef).inner;
    if (inner.kind === "primitive") {
      const primitive = inner as PrimitiveRef;
      switch (primitive.primitive) {
        case "string":
          if (paramName.includes("intent")) return `'{"action":"play","entityId":"entity-123"}'`;
          if (paramName.includes("appid")) return `"app123"`;
          if (paramName.includes("entity")) return `"entity-123"`;
          if (paramName.includes("page")) return `"details"`;
          if (paramName.includes("error")) return `"network"`;
          if (paramName.includes("message")) return `"Connection failed"`;
          if (paramName.includes("event")) return `"user_action"`;
          if (paramName.includes("data")) return `'{"action":"favorite"}'`;
          if (paramName.includes("name")) return `"My Device"`;
          if (paramName.includes("id")) return `"12345"`;
          if (paramName.includes("date") || paramName.includes("time")) return `"2026-09-16T05:43:00.000Z"`;
          if (paramName.includes("watchedon")) return `"2026-09-16T05:43:00.000Z"`;
          return `"${param.name}"`;
        case "bool":
          return "true";
        case "unsigned":
        case "double":
          if (paramName.includes("progress")) return "0.75";
          if (paramName.includes("id")) return "1";
          return "0";
      }
    }
    return "undefined";
  } else if (type.kind === "named") {
    const named = type as NamedRef;
    // Handle enum types with realistic values
    if (named.name === "AgePolicy") return `"app:adult"`;
    if (named.name === "ErrorType") return `"network"`;
    return `${named.name}`;
  } else if (type.kind === "array") {
    return `["${param.name}1", "${param.name}2"]`;
  }
  
  return "null";
}

function generateExampleValueForType(type: TypeRef): string {
  if (type.kind === "primitive") {
    const primitive = type as PrimitiveRef;
    switch (primitive.primitive) {
      case "string":
        return `"1.2.3"`;
      case "bool":
        return "true";
      case "unsigned":
      case "double":
        return "0";
    }
  }
  return `"value"`;
}

function typeRefToTS(ref: TypeRef): string {
  switch (ref.kind) {
    case "primitive":
      return primitiveToTS(ref as PrimitiveRef);
    case "named": {
      const nr = ref as NamedRef;
      return nr.module ? `${nr.module}.${nr.name}` : nr.name;
    }
    case "array":
      return `${typeRefToTS((ref as ArrayRef).items)}[]`;
    case "optional":
      return `${typeRefToTS((ref as OptionalRef).inner)} | undefined`;
  }
}

function primitiveToTS(ref: PrimitiveRef): string {
  switch (ref.primitive) {
    case "bool":
      return "boolean";
    case "string":
      return "string";
    case "unsigned":
    case "double":
      return "number";
  }
}

// ---------------------------------------------------------------------------
// Register
// ---------------------------------------------------------------------------

registerFullASTGenerator("inject-js-types", generate, "web");