/**
 * inject-js-types TypeScript definition generator.
 *
 * Emits a single TypeScript definition file (firebolt-inject.d.ts) that matches
 * the inject-js factory/builder pattern, enabling VS Code intellisense and API
 * documentation for app developers.
 *
 * Only web-platform modules (platform: "web" | "both") are included.
 */

import {
  CanonicalAST,
  Module,
  TypeDecl,
  Method,
  Param,
  TypeRef,
  OptionalRef,
  PrimitiveRef,
  NamedRef,
  ArrayRef,
  ObjectTypeDecl,
} from "../ast/types";
import { GenConfig, GeneratorOutput, registerFullASTGenerator, extractConstraints, formatConstraintNote } from "./index";

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

function generate(ast: CanonicalAST, _config: GenConfig): GeneratorOutput[] {
  const lines: string[] = [];

  lines.push(`// Auto-generated by firebolt-gen — do not edit manually.`);
  lines.push(`// TypeScript definitions for inject-js factory/builder pattern`);
  lines.push(``);

  // Emit core interfaces
  lines.push(...emitFireboltTransportInterface());
  lines.push(``);
  lines.push(...emitExtensionSchemaInterface());
  lines.push(``);
  lines.push(...emitFactoryConfigInterface());
  lines.push(``);
  lines.push(...emitFireboltBuilderInterface());
  lines.push(``);

  // Filter to web + both platform modules only
  const webModules = ast.modules.filter(
    (m) => m.platform === "web" || m.platform === "both"
  );

  // Emit module namespaces
  for (const mod of webModules) {
    lines.push(...emitModuleNamespace(mod));
    lines.push(``);
  }

  // Emit FireboltClient interface
  lines.push(...emitFireboltClientInterface(webModules));
  lines.push(``);

  // Emit factory function declaration
  lines.push(...emitFactoryFunction());
  lines.push(``);

  // Emit export statements
  lines.push(...emitExportStatements());
  lines.push(``);
  lines.push(`// Export Firebolt namespace for direct consumption`);
  lines.push(`export as namespace Firebolt;`);

  return [
    {
      filePath: "inject-js/firebolt-inject.d.ts",
      content: lines.join("\n"),
    },
  ];
}

// ---------------------------------------------------------------------------
// Core interface generation
// ---------------------------------------------------------------------------

function emitFireboltTransportInterface(): string[] {
  return [
    `/** Transport interface for Firebolt communication */`,
    `interface FireboltTransport {`,
    `  /** Send data to the Firebolt backend */`,
    `  send(data: string): void;`,
    `  /** Open the transport connection */`,
    `  open(): void;`,
    `  /** Close the transport connection */`,
    `  close(): void;`,
    `  /** Callback for incoming messages */`,
    `  onMessage?: (raw: string) => void;`,
    `  /** Callback when connection opens */`,
    `  onOpen?: () => void;`,
    `  /** Callback when connection closes */`,
    `  onClose?: () => void;`,
    `  /** Callback when errors occur */`,
    `  onError?: (error: unknown) => void;`,
    `}`,
  ];
}

function emitExtensionSchemaInterface(): string[] {
  return [
    `/** Extension schema for dynamic API extension */`,
    `interface ExtensionSchema {`,
    `  /** Module name */`,
    `  name: string;`,
    `  /** Methods without parameters */`,
    `  methods?: string[];`,
    `  /** Event names */`,
    `  events?: string[];`,
    `  /** Methods with object parameters */`,
    `  methodsWithObject?: string[];`,
    `}`,
  ];
}

function emitFactoryConfigInterface(): string[] {
  return [
    `/** Configuration for the Firebolt factory */`,
    `interface FactoryConfig {`,
    `  /** Transport implementation */`,
    `  transport: FireboltTransport;`,
    `  /** Extension schema (JSON string or typed array) */`,
    `  extensionSchema?: string | ExtensionSchema[];`,
    `  /** Enable debug mode */`,
    `  enableDebug?: boolean;`,
    `}`,
  ];
}

function emitFireboltBuilderInterface(): string[] {
  return [
    `/** Builder for Firebolt client instance */`,
    `interface FireboltBuilder {`,
    `  /** Build the Firebolt client instance */`,
    `  build(): Promise<FireboltClient>;`,
    `}`,
  ];
}

function emitFireboltClientInterface(modules: Module[]): string[] {
  const lines: string[] = [
    `/** Firebolt client with all module namespaces */`,
    `interface FireboltClient {`,
  ];

  for (const mod of modules) {
    lines.push(`  ${mod.name}: typeof Firebolt.${mod.name};`);
  }

  lines.push(`  /** Cleanup and close connection */`);
  lines.push(`  cleanup(): void;`);
  lines.push(`}`);

  return lines;
}

function emitFactoryFunction(): string[] {
  return [
    `/** Factory function to create Firebolt builder */`,
    `declare function factory(config: FactoryConfig): FireboltBuilder;`,
  ];
}

function emitExportStatements(): string[] {
  return [
    `export { factory, FireboltClient, FireboltTransport, FactoryConfig, ExtensionSchema };`,
  ];
}

// ---------------------------------------------------------------------------
// Module namespace generation
// ---------------------------------------------------------------------------

function emitModuleNamespace(module: Module): string[] {
  const lines: string[] = [
    `declare namespace Firebolt {`,
    `  namespace ${module.name} {`,
  ];

  // Emit type declarations (enums, interfaces)
  for (const decl of module.types) {
    const typeLines = emitTypeDecl(decl);
    for (const line of typeLines) {
      lines.push(`    ${line}`);
    }
    lines.push(``);
  }

  // Emit parameter interfaces for methods with parameters
  for (const method of module.methods) {
    if (method.kind === "call" && method.params.length > 0) {
      const paramInterface = emitParamInterface(method);
      if (paramInterface.length > 0) {
        for (const line of paramInterface) {
          lines.push(`    ${line}`);
        }
        lines.push(``);
      }
    }
  }

  // Emit method signatures
  for (const method of module.methods) {
    const methodLines = emitMethod(method, module.name);
    for (const line of methodLines) {
      lines.push(`    ${line}`);
    }
    lines.push(``);
  }

  lines.push(`  }`);
  lines.push(`}`);

  return lines;
}

// ---------------------------------------------------------------------------
// Helper functions (adapted from typescript.ts)
// ---------------------------------------------------------------------------

function getParamInterfaceName(method: Method): string {
  // Capitalize first letter of method name
  const capitalizedMethod = method.name.charAt(0).toUpperCase() + method.name.slice(1);
  return `${capitalizedMethod}Params`;
}

function emitParamInterface(method: Method): string[] {
  if (method.params.length === 0) {
    return [];
  }

  const interfaceName = getParamInterfaceName(method);
  const lines: string[] = [];

  lines.push(`/** Parameters for ${method.name} */`);
  lines.push(`interface ${interfaceName} {`);

  for (const param of method.params) {
    const isOptional = param.type.kind === "optional";
    const opt = isOptional ? "?" : "";
    const ref = isOptional
      ? (param.type as OptionalRef).inner
      : param.type;
    const inner = typeRefToTS(ref);
    const c = extractConstraints(ref);
    if (c) lines.push(`  /** Constraints: ${formatConstraintNote(c)} */`);
    lines.push(`  ${param.name}${opt}: ${inner};`);
  }

  lines.push(`}`);
  return lines;
}


function emitTypeDecl(decl: TypeDecl): string[] {
  if (decl.kind === "enum") {
    return emitEnum(decl);
  }
  if (decl.kind === "object") {
    return emitObject(decl);
  }
  return [`// [unsupported TypeDecl kind: ${decl.kind}]`];
}

function emitEnum(decl: TypeDecl): string[] {
  const literals = (decl as any).values.map((v: any) => `"${v.serializedId}"`).join(" | ");
  const lines: string[] = [];
  if (decl.description) {
    lines.push(`/** ${decl.description} */`);
  }
  lines.push(`type ${decl.name} = ${literals};`);
  return lines;
}

function emitObject(decl: ObjectTypeDecl): string[] {
  const lines: string[] = [];
  if (decl.description) {
    lines.push(`/** ${decl.description} */`);
  }
  lines.push(`interface ${decl.name} {`);
  for (const prop of decl.properties) {
    const opt = !prop.required ? "?" : "";
    const ref =
      !prop.required && prop.type.kind === "optional"
        ? (prop.type as OptionalRef).inner
        : prop.type;
    const inner = typeRefToTS(ref);
    const c = extractConstraints(ref);
    if (c) lines.push(`  /** Constraints: ${formatConstraintNote(c)} */`);
    lines.push(`  ${prop.name}${opt}: ${inner};`);
  }
  lines.push(`}`);
  return lines;
}

function emitMethod(method: Method, moduleName: string): string[] {
  if (method.kind === "call") {
    return emitCallMethod(method, moduleName);
  }
  return emitSubscribeMethod(method);
}

function emitCallMethod(method: Method, moduleName: string): string[] {
  let paramStr: string;
  
  if (method.params.length === 0) {
    // No parameters
    paramStr = "";
  } else {
    // All methods with parameters use parameter interface
    const interfaceName = getParamInterfaceName(method);
    paramStr = `params: ${interfaceName}`;
  }
  
  const resultType =
    method.result === null ? "void" : typeRefToTS(method.result);
  const constraintLines = collectConstraintLines(method);
  const exampleLines = emitExample(method, moduleName);
  
  let doc = `/** ${method.description}`;
  if (constraintLines.length) {
    doc += `\n   * Constraints: ${constraintLines.join(" | ")}`;
  }
  if (exampleLines.length) {
    doc += `\n   * @example`;
    for (const line of exampleLines) {
      doc += `\n   *   ${line}`;
    }
  }
  doc += ` */`;
  
  return [
    doc,
    `function ${method.name}(${paramStr}): Promise<${resultType}>;`,
  ];
}

function emitSubscribeMethod(method: Method): string[] {
  const callbackType =
    method.result === null ? "(event: null, cancelled: boolean) => void" : `(event: ${typeRefToTS(method.result)}, cancelled: boolean) => void`;
  const paramStr = method.params.map(paramToTS).join(", ");
  const sep = paramStr ? ", " : "";
  const constraintLines = collectConstraintLines(method);
  const doc = constraintLines.length
    ? `/** ${method.description}\n   * Constraints — event payload: ${constraintLines.join(" | ")} */`
    : `/** ${method.description} */`;
  return [
    doc,
    `function ${method.name}(${paramStr}${sep}callback: ${callbackType}): () => void;`,
  ];
}

function collectConstraintLines(method: Method): string[] {
  const notes: string[] = [];
  for (const p of method.params) {
    const c = extractConstraints(p.type);
    if (c) notes.push(`${p.name}: ${formatConstraintNote(c)}`);
  }
  if (method.result) {
    const c = extractConstraints(method.result);
    if (c) notes.push(formatConstraintNote(c));
  }
  return notes;
}

function paramToTS(p: Param): string {
  if (p.type.kind === "optional") {
    return `${p.name}?: ${typeRefToTS((p.type as OptionalRef).inner)}`;
  }
  return `${p.name}: ${typeRefToTS(p.type)}`;
}

function emitExample(method: Method, moduleName: string): string[] {
  if (method.params.length === 0) {
    return [];
  }

  const lines: string[] = [];
  const interfaceName = getParamInterfaceName(method);
  
  // Generate example values for each parameter
  const exampleParams: string[] = [];
  for (const param of method.params) {
    const isOptional = param.type.kind === "optional";
    // Skip optional parameters in examples to keep them clean
    if (isOptional) continue;
    
    const exampleValue = generateExampleValue(param);
    exampleParams.push(`  ${param.name}: ${exampleValue}`);
  }
  
  lines.push(`const params: Firebolt.${moduleName}.${interfaceName} = {`);
  lines.push(...exampleParams);
  lines.push(`};`);
  lines.push(`Firebolt.${moduleName}.${method.name}(params);`);
  
  return lines;
}

function generateExampleValue(param: Param): string {
  const type = param.type;
  const paramName = param.name.toLowerCase();
  
  if (type.kind === "primitive") {
    const primitive = type as PrimitiveRef;
    switch (primitive.primitive) {
      case "string":
        // Generate more realistic example values based on parameter name
        if (paramName.includes("intent")) return `'{"action":"play","entityId":"entity-123"}'`;
        if (paramName.includes("appid")) return `"app123"`;
        if (paramName.includes("entity")) return `"entity-123"`;
        if (paramName.includes("page")) return `"details"`;
        if (paramName.includes("error")) return `"network"`;
        if (paramName.includes("message")) return `"Connection failed"`;
        if (paramName.includes("event")) return `"user_action"`;
        if (paramName.includes("data")) return `'{"action":"favorite"}'`;
        if (paramName.includes("name")) return `"My Device"`;
        if (paramName.includes("id")) return `"12345"`;
        if (paramName.includes("date") || paramName.includes("time")) return `"2026-09-16T05:43:00.000Z"`;
        if (paramName.includes("watchedon")) return `"2026-09-16T05:43:00.000Z"`;
        return `"${param.name}"`;
      case "bool":
        return "true";
      case "unsigned":
      case "double":
        // Generate more realistic numeric examples
        if (paramName.includes("progress")) return "0.75";
        if (paramName.includes("id")) return "1";
        return "0";
    }
  } else if (type.kind === "optional") {
    const inner = (type as OptionalRef).inner;
    if (inner.kind === "primitive") {
      const primitive = inner as PrimitiveRef;
      switch (primitive.primitive) {
        case "string":
          if (paramName.includes("intent")) return `'{"action":"play","entityId":"entity-123"}'`;
          if (paramName.includes("appid")) return `"app123"`;
          if (paramName.includes("entity")) return `"entity-123"`;
          if (paramName.includes("page")) return `"details"`;
          if (paramName.includes("error")) return `"network"`;
          if (paramName.includes("message")) return `"Connection failed"`;
          if (paramName.includes("event")) return `"user_action"`;
          if (paramName.includes("data")) return `'{"action":"favorite"}'`;
          if (paramName.includes("name")) return `"My Device"`;
          if (paramName.includes("id")) return `"12345"`;
          if (paramName.includes("date") || paramName.includes("time")) return `"2026-09-16T05:43:00.000Z"`;
          if (paramName.includes("watchedon")) return `"2026-09-16T05:43:00.000Z"`;
          return `"${param.name}"`;
        case "bool":
          return "true";
        case "unsigned":
        case "double":
          if (paramName.includes("progress")) return "0.75";
          if (paramName.includes("id")) return "1";
          return "0";
      }
    }
    return "undefined";
  } else if (type.kind === "named") {
    const named = type as NamedRef;
    // Handle enum types with realistic values
    if (named.name === "AgePolicy") return `"app:adult"`;
    if (named.name === "ErrorType") return `"network"`;
    return `${named.name}`;
  } else if (type.kind === "array") {
    return `["${param.name}1", "${param.name}2"]`;
  }
  
  return "null";
}

function typeRefToTS(ref: TypeRef): string {
  switch (ref.kind) {
    case "primitive":
      return primitiveToTS(ref as PrimitiveRef);
    case "named": {
      const nr = ref as NamedRef;
      return nr.module ? `${nr.module}.${nr.name}` : nr.name;
    }
    case "array":
      return `${typeRefToTS((ref as ArrayRef).items)}[]`;
    case "optional":
      return `${typeRefToTS((ref as OptionalRef).inner)} | undefined`;
  }
}

function primitiveToTS(ref: PrimitiveRef): string {
  switch (ref.primitive) {
    case "bool":
      return "boolean";
    case "string":
      return "string";
    case "unsigned":
    case "double":
      return "number";
  }
}

// ---------------------------------------------------------------------------
// Register
// ---------------------------------------------------------------------------

registerFullASTGenerator("inject-js-types", generate, "web");