/**
 * Kotlin/JS `.kt` generator.
 *
 * Conventions (from generator-conventions.md):
 *   - EnumType → enum class with `val value: String` constructor when
 *     wire values contain non-identifier chars; else plain enum.
 *   - ObjectType → external interface
 *   - Method(call) → fun in external object, returns Promise<T>
 *   - Optional params → = definedExternally
 *   - Method(subscribe) → callback: (T) -> Unit, returns () -> Unit
 *   - Output: generated/kt/<Module>.kt
 */

import {
  ArrayRef,
  EnumTypeDecl,
  Method,
  Module,
  NamedRef,
  ObjectTypeDecl,
  OptionalRef,
  Param,
  PrimitiveRef,
  TypeDecl,
  TypeRef,
} from "../ast/types";
import { GenConfig, GeneratorOutput, extractConstraints, formatConstraintNote, registerGenerator } from "./index";

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

function generate(module: Module, _config: GenConfig): GeneratorOutput[] {
  const packageName = module.name.toLowerCase();
  const lines: string[] = [];

  lines.push(`// Auto-generated by firebolt-gen — do not edit manually.`);
  lines.push(`@file:JsModule("@firebolt-js/sdk")`);
  lines.push(`@file:JsNonModule`);
  lines.push(``);
  lines.push(`package firebolt.${packageName}`);
  lines.push(``);
  lines.push(`import kotlin.js.Promise`);
  lines.push(``);

  for (const decl of module.types) {
    lines.push(...emitTypeDecl(decl));
    lines.push(``);
  }

  // external object for methods
  lines.push(`external object ${module.name} {`);
  for (const method of module.methods) {
    lines.push(...emitMethod(method).map((l) => `    ${l}`));
    lines.push(``);
  }
  lines.push(`}`);
  lines.push(``);

  return [
    {
      filePath: `kt/${module.name}.kt`,
      content: lines.join("\n"),
    },
  ];
}

// ---------------------------------------------------------------------------
// Type declarations
// ---------------------------------------------------------------------------

function emitTypeDecl(decl: TypeDecl): string[] {
  if (decl.kind === "enum") return emitEnum(decl);
  if (decl.kind === "object") return emitObject(decl);
  return [`// [unsupported TypeDecl kind: ${(decl as TypeDecl).kind}]`];
}

function emitEnum(decl: EnumTypeDecl): string[] {
  // If any wire value contains non-identifier chars, use value class pattern
  const needsValueClass = decl.values.some((v) => /[^a-zA-Z0-9_]/.test(v.serializedId));
  const lines: string[] = [];
  if (needsValueClass) {
    lines.push(`enum class ${decl.name}(val value: String) {`);
    decl.values.forEach((v, i) => {
      const comma = i < decl.values.length - 1 ? "," : ";";
      lines.push(`    ${v.identifier}("${v.serializedId}")${comma}`);
    });
    lines.push(`}`);
  } else {
    lines.push(`enum class ${decl.name} {`);
    decl.values.forEach((v, i) => {
      const comma = i < decl.values.length - 1 ? "," : "";
      lines.push(`    ${v.identifier}${comma}`);
    });
    lines.push(`}`);
  }
  return lines;
}

function emitObject(decl: ObjectTypeDecl): string[] {
  const lines: string[] = [];
  lines.push(`external interface ${decl.name} {`);
  for (const prop of decl.properties) {
    const isOpt = !prop.required;
    const ref =
      isOpt && prop.type.kind === "optional"
        ? (prop.type as OptionalRef).inner
        : prop.type;
    const ktType = isOpt ? `${typeRefToKt(ref)}?` : typeRefToKt(ref);
    const c = extractConstraints(ref);
    const note = c ? ` // ${formatConstraintNote(c)}` : "";
    lines.push(`    val ${prop.name}: ${ktType}${note}`);
  }
  lines.push(`}`);
  return lines;
}

// ---------------------------------------------------------------------------
// Methods
// ---------------------------------------------------------------------------

function emitMethod(method: Method): string[] {
  if (method.kind === "call") return emitCallMethod(method);
  return emitSubscribeMethod(method);
}

function emitCallMethod(method: Method): string[] {
  const params = method.params.map(paramToKt).join(", ");
  const resultType = method.result === null ? "Unit" : typeRefToKt(method.result);
  const lines: string[] = [];
  const constraintNote = buildConstraintNote(method);
  if (constraintNote) lines.push(`/** ${constraintNote} */`);
  lines.push(`fun ${method.name}(${params}): Promise<${resultType}>`);
  return lines;
}

function emitSubscribeMethod(method: Method): string[] {
  const params = method.params.map(paramToKt);
  const callbackType =
    method.result === null
      ? `() -> Unit`
      : `(${typeRefToKt(method.result)}) -> Unit`;
  params.push(`callback: ${callbackType}`);
  const lines: string[] = [];
  const constraintNote = buildConstraintNote(method);
  if (constraintNote) lines.push(`/** ${constraintNote} */`);
  lines.push(`fun ${method.name}(${params.join(", ")}): () -> Unit`);
  return lines;
}

function buildConstraintNote(method: Method): string {
  const notes: string[] = [];
  for (const p of method.params) {
    const c = extractConstraints(p.type);
    if (c) notes.push(`${p.name}: ${formatConstraintNote(c)}`);
  }
  if (method.result) {
    const c = extractConstraints(method.result);
    if (c) notes.push(`result: ${formatConstraintNote(c)}`);
  }
  return notes.length ? `Constraints — ${notes.join(" | ")}` : "";
}

function paramToKt(p: Param): string {
  if (p.type.kind === "optional") {
    return `${p.name}: ${typeRefToKt((p.type as OptionalRef).inner)}? = definedExternally`;
  }
  return `${p.name}: ${typeRefToKt(p.type)}`;
}

// ---------------------------------------------------------------------------
// TypeRef → Kotlin string
// ---------------------------------------------------------------------------

function typeRefToKt(ref: TypeRef): string {
  switch (ref.kind) {
    case "primitive":
      return primitiveToKt(ref as PrimitiveRef);
    case "named": {
      const nr = ref as NamedRef;
      return nr.module ? `${nr.module}.${nr.name}` : nr.name;
    }
    case "array":
      return `Array<${typeRefToKt((ref as ArrayRef).items)}>`;
    case "optional":
      return `${typeRefToKt((ref as OptionalRef).inner)}?`;
  }
}

function primitiveToKt(ref: PrimitiveRef): string {
  switch (ref.primitive) {
    case "bool":
      return "Boolean";
    case "string":
      return "String";
    case "unsigned":
      return "Int";
    case "double":
      return "Double";
  }
}

// ---------------------------------------------------------------------------
// Register
// ---------------------------------------------------------------------------

registerGenerator("kt", generate, "web");
