/**
 * Python `.pyi` type stub + `_protocol.py` abstract base generator.
 *
 * Conventions (from generator-conventions.md):
 *   - EnumType → Literal[...] in .pyi; str+Enum class in _protocol.py
 *   - ObjectType → TypedDict in .pyi; plain dataclass in _protocol.py
 *   - Method(call) → async def stub in .pyi; @abstractmethod in _protocol.py
 *   - Method(subscribe) → Callable[[T], None] callback returning Callable[[], None]
 *   - format:"date-time" string params/props → datetime in .pyi
 *   - Output: generated/py/<module>.pyi and generated/py/<module>_protocol.py
 */

import {
  ArrayRef,
  EnumTypeDecl,
  Method,
  Module,
  NamedRef,
  ObjectTypeDecl,
  OptionalRef,
  Param,
  PrimitiveRef,
  TypeDecl,
  TypeRef,
} from "../ast/types";
import { GenConfig, GeneratorOutput, formatConstraintNote, registerGenerator } from "./index";

const modName = (name: string) => name.toLowerCase();

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

function generate(module: Module, _config: GenConfig): GeneratorOutput[] {
  return [emitStub(module), emitProtocol(module)];
}

// ---------------------------------------------------------------------------
// .pyi stub
// ---------------------------------------------------------------------------

function emitStub(module: Module): GeneratorOutput {
  const lines: string[] = [];
  const hasDt = moduleUsesDatetime(module);

  lines.push(`# Auto-generated by firebolt-gen — do not edit manually.`);
  lines.push(`from __future__ import annotations`);
  lines.push(`from typing import Callable, Literal, Optional`);
  if (hasDt) lines.push(`from datetime import datetime`);
  const hasAnnotated = moduleUsesAnnotated(module);
  if (hasAnnotated) lines.push(`from typing import Annotated`);
  lines.push(`from typing_extensions import TypedDict`);
  lines.push(``);

  for (const decl of module.types) {
    lines.push(...emitStubTypeDecl(decl));
    lines.push(``);
  }

  lines.push(`class ${module.name}:`);
  for (const method of module.methods) {
    lines.push(...emitStubMethod(method).map((l) => `    ${l}`));
    lines.push(``);
  }

  return {
    filePath: `py/${modName(module.name)}.pyi`,
    content: lines.join("\n"),
  };
}

function emitStubTypeDecl(decl: TypeDecl): string[] {
  if (decl.kind === "enum") return emitStubEnum(decl);
  if (decl.kind === "object") return emitStubObject(decl);
  return [`# [unsupported TypeDecl kind: ${(decl as TypeDecl).kind}]`];
}

function emitStubEnum(decl: EnumTypeDecl): string[] {
  const literals = decl.values.map((v) => `"${v.serializedId}"`).join(", ");
  return [`${decl.name} = Literal[${literals}]`];
}

function emitStubObject(decl: ObjectTypeDecl): string[] {
  const lines: string[] = [];
  lines.push(`class ${decl.name}(TypedDict):`);
  for (const prop of decl.properties) {
    const isOpt = !prop.required;
    const innerRef =
      isOpt && prop.type.kind === "optional"
        ? (prop.type as OptionalRef).inner
        : prop.type;
    const pyType = isOpt ? `Optional[${typeRefToPy(innerRef)}]` : typeRefToPy(innerRef);
    lines.push(`    ${prop.name}: ${pyType}`);
  }
  return lines;
}

function emitStubMethod(method: Method): string[] {
  if (method.kind === "call") return emitStubCallMethod(method);
  return emitStubSubscribeMethod(method);
}

function emitStubCallMethod(method: Method): string[] {
  const params = ["self", ...method.params.map(paramToPy)].join(", ");
  const retType = method.result === null ? "None" : typeRefToPy(method.result);
  return [
    `async def ${method.name}(${params}) -> ${retType}: ...`,
  ];
}

function emitStubSubscribeMethod(method: Method): string[] {
  const params = method.params.map(paramToPy);
  const cbType =
    method.result === null
      ? `Callable[[], None]`
      : `Callable[[${typeRefToPy(method.result)}], None]`;
  params.push(`callback: ${cbType}`);
  return [
    `def ${method.name}(self, ${params.join(", ")}) -> Callable[[], None]: ...`,
  ];
}

function paramToPy(p: Param): string {
  if (p.type.kind === "optional") {
    return `${p.name}: Optional[${typeRefToPy((p.type as OptionalRef).inner)}] = None`;
  }
  return `${p.name}: ${typeRefToPy(p.type)}`;
}

// ---------------------------------------------------------------------------
// _protocol.py
// ---------------------------------------------------------------------------

function emitProtocol(module: Module): GeneratorOutput {
  const lines: string[] = [];
  const hasDt = moduleUsesDatetime(module);

  lines.push(`# Auto-generated by firebolt-gen — do not edit manually.`);
  lines.push(`from __future__ import annotations`);
  lines.push(`from abc import ABC, abstractmethod`);
  lines.push(`from enum import Enum`);
  lines.push(`from typing import Callable, Optional`);
  if (hasDt) lines.push(`from datetime import datetime`);
  lines.push(``);

  for (const decl of module.types) {
    lines.push(...emitProtocolTypeDecl(decl));
    lines.push(``);
  }

  lines.push(`class ${module.name}Protocol(ABC):`);
  for (const method of module.methods) {
    lines.push(...emitProtocolMethod(method).map((l) => `    ${l}`));
    lines.push(``);
  }

  return {
    filePath: `py/${modName(module.name)}_protocol.py`,
    content: lines.join("\n"),
  };
}

function emitProtocolTypeDecl(decl: TypeDecl): string[] {
  if (decl.kind === "enum") return emitProtocolEnum(decl);
  if (decl.kind === "object") return emitProtocolObject(decl);
  return [`# [unsupported TypeDecl kind: ${(decl as TypeDecl).kind}]`];
}

function emitProtocolEnum(decl: EnumTypeDecl): string[] {
  const lines: string[] = [];
  lines.push(`class ${decl.name}(str, Enum):`);
  for (const v of decl.values) {
    lines.push(`    ${v.identifier} = "${v.serializedId}"`);
  }
  return lines;
}

function emitProtocolObject(decl: ObjectTypeDecl): string[] {
  const lines: string[] = [];
  lines.push(`class ${decl.name}:`);
  lines.push(`    def __init__(self`);
  for (const prop of decl.properties) {
    const isOpt = !prop.required;
    const innerRef =
      isOpt && prop.type.kind === "optional"
        ? (prop.type as OptionalRef).inner
        : prop.type;
    const pyType = isOpt ? `Optional[${typeRefToPy(innerRef)}]` : typeRefToPy(innerRef);
    const default_ = isOpt ? ` = None` : ``;
    lines.push(`        ,${prop.name}: ${pyType}${default_}`);
  }
  lines.push(`    ) -> None:`);
  for (const prop of decl.properties) {
    lines.push(`        self.${prop.name} = ${prop.name}`);
  }
  return lines;
}

function emitProtocolMethod(method: Method): string[] {
  if (method.kind === "call") return emitProtocolCallMethod(method);
  return emitProtocolSubscribeMethod(method);
}

function emitProtocolCallMethod(method: Method): string[] {
  const params = ["self", ...method.params.map(paramToPy)].join(", ");
  const retType = method.result === null ? "None" : typeRefToPy(method.result);
  return [
    `@abstractmethod`,
    `async def ${method.name}(${params}) -> ${retType}:`,
    `    ...`,
  ];
}

function emitProtocolSubscribeMethod(method: Method): string[] {
  const params = method.params.map(paramToPy);
  const cbType =
    method.result === null
      ? `Callable[[], None]`
      : `Callable[[${typeRefToPy(method.result)}], None]`;
  params.push(`callback: ${cbType}`);
  return [
    `@abstractmethod`,
    `def ${method.name}(self, ${params.join(", ")}) -> Callable[[], None]:`,
    `    ...`,
  ];
}

// ---------------------------------------------------------------------------
// TypeRef → Python string
// ---------------------------------------------------------------------------

function typeRefToPy(ref: TypeRef): string {
  switch (ref.kind) {
    case "primitive":
      return primitiveToPy(ref as PrimitiveRef);
    case "named": {
      const nr = ref as NamedRef;
      return nr.name; // cross-module not needed in PoC
    }
    case "array":
      return `list[${typeRefToPy((ref as ArrayRef).items)}]`;
    case "optional":
      return `Optional[${typeRefToPy((ref as OptionalRef).inner)}]`;
  }
}

function primitiveToPy(ref: PrimitiveRef): string {
  // Rule 5 (Python): date-time → datetime
  if (ref.format === "date-time") return "datetime";
  switch (ref.primitive) {
    case "bool":
      return "bool";
    case "string":
      // Rule 7 (Python): constrained string → Annotated[str, "<note>"]
      if (ref.constraints) return `Annotated[str, "${formatConstraintNote(ref.constraints)}"]`;
      return "str";
    case "unsigned":
    case "double":
      // Rule 7 (Python): constrained number → Annotated[float, "<note>"]
      if (ref.constraints) return `Annotated[float, "${formatConstraintNote(ref.constraints)}"]`;
      return "float";
  }
}

// ---------------------------------------------------------------------------
// Helpers: does this module use datetime / Annotated anywhere?
// ---------------------------------------------------------------------------

function moduleUsesDatetime(module: Module): boolean {
  return module.methods.some((m) =>
    m.params.some((p) => typeRefUsesDatetime(p.type))
  );
}

function typeRefUsesDatetime(ref: TypeRef): boolean {
  if (ref.kind === "primitive") return (ref as PrimitiveRef).format === "date-time";
  if (ref.kind === "optional") return typeRefUsesDatetime((ref as OptionalRef).inner);
  if (ref.kind === "array") return typeRefUsesDatetime((ref as ArrayRef).items);
  return false;
}

function moduleUsesAnnotated(module: Module): boolean {
  // Check method params and results
  for (const m of module.methods) {
    for (const p of m.params) if (refUsesAnnotated(p.type)) return true;
    if (m.result && refUsesAnnotated(m.result)) return true;
  }
  // Check object type properties
  for (const decl of module.types) {
    if (decl.kind === "object") {
      for (const prop of decl.properties) {
        if (refUsesAnnotated(prop.type)) return true;
      }
    }
  }
  return false;
}

function refUsesAnnotated(ref: TypeRef): boolean {
  if (ref.kind === "primitive") return !!(ref as PrimitiveRef).constraints;
  if (ref.kind === "optional") return refUsesAnnotated((ref as OptionalRef).inner);
  if (ref.kind === "array") return refUsesAnnotated((ref as ArrayRef).items);
  return false;
}

// ---------------------------------------------------------------------------
// Register
// ---------------------------------------------------------------------------

registerGenerator("py", generate, "native");
