/**
 * ReScript `.res` generator.
 *
 * Conventions (from generator-conventions.md):
 *   - EnumType → @unboxed variant type with @as decorator per value (using serializedId)
 *   - ObjectType → record type
 *   - Method(call) → @val @scope external with labelled optional args (~param=?)
 *   - Method(subscribe) → returns (unit => unit) unsubscribe fn
 *   - Output: generated/res/<Module>.res
 */

import {
  ArrayRef,
  EnumTypeDecl,
  Method,
  Module,
  NamedRef,
  ObjectTypeDecl,
  OptionalRef,
  Param,
  PrimitiveRef,
  TypeDecl,
  TypeRef,
} from "../ast/types";
import { GenConfig, GeneratorOutput, extractConstraints, formatConstraintNote, registerGenerator } from "./index";

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

function generate(module: Module, _config: GenConfig): GeneratorOutput[] {
  const lines: string[] = [];

  lines.push(`/* Auto-generated by firebolt-gen — do not edit manually. */`);
  lines.push(``);

  for (const decl of module.types) {
    lines.push(...emitTypeDecl(decl));
    lines.push(``);
  }

  for (const method of module.methods) {
    lines.push(...emitMethod(method, module.name));
    lines.push(``);
  }

  return [
    {
      filePath: `res/${module.name}.res`,
      content: lines.join("\n"),
    },
  ];
}

// ---------------------------------------------------------------------------
// Type declarations
// ---------------------------------------------------------------------------

function emitTypeDecl(decl: TypeDecl): string[] {
  if (decl.kind === "enum") return emitEnum(decl);
  if (decl.kind === "object") return emitObject(decl);
  return [`/* [unsupported TypeDecl kind: ${(decl as TypeDecl).kind}] */`];
}

function emitEnum(decl: EnumTypeDecl): string[] {
  const lines: string[] = [];
  lines.push(`@unboxed`);
  lines.push(`type ${lcFirst(decl.name)} =`);
  for (const v of decl.values) {
    lines.push(`  | @as("${v.serializedId}") ${v.identifier}`);
  }
  return lines;
}

function emitObject(decl: ObjectTypeDecl): string[] {
  const lines: string[] = [];
  lines.push(`type ${lcFirst(decl.name)} = {`);
  for (const prop of decl.properties) {
    const ref =
      !prop.required && prop.type.kind === "optional"
        ? (prop.type as OptionalRef).inner
        : prop.type;
    const t = !prop.required && prop.type.kind === "optional"
      ? `option<${typeRefToRes(ref)}>`
      : typeRefToRes(ref);
    const c = extractConstraints(ref);
    const note = c ? ` /* ${formatConstraintNote(c)} */` : "";
    lines.push(`  ${prop.name}: ${t},${note}`);
  }
  lines.push(`}`);
  return lines;
}

// ---------------------------------------------------------------------------
// Methods
// ---------------------------------------------------------------------------

function emitMethod(method: Method, moduleName: string): string[] {
  if (method.kind === "call") return emitCallMethod(method, moduleName);
  return emitSubscribeMethod(method, moduleName);
}

function emitCallMethod(method: Method, moduleName: string): string[] {
  const params = method.params.map(paramToRes).join(", ");
  const sep = params ? ", " : "";
  const resultType =
    method.result === null ? "unit" : `promise<${typeRefToRes(method.result)}>`;
  const lines: string[] = [];
  const constraintNote = buildConstraintNote(method);
  if (constraintNote) lines.push(`/* ${constraintNote} */`);
  lines.push(`@val @scope("${moduleName}")`);
  lines.push(`external ${lcFirst(method.name)}: (${params}${sep}unit) => ${resultType} = "${method.name}"`);
  return lines;
}

function emitSubscribeMethod(method: Method, moduleName: string): string[] {
  const params = method.params.map(paramToRes).join(", ");
  const sep = params ? ", " : "";
  const callbackType =
    method.result === null
      ? `(unit => unit)`
      : `(${typeRefToRes(method.result)} => unit)`;
  const lines: string[] = [];
  const constraintNote = buildConstraintNote(method);
  if (constraintNote) lines.push(`/* ${constraintNote} */`);
  lines.push(`@val @scope("${moduleName}")`);
  lines.push(`external ${lcFirst(method.name)}: (${params}${sep}~callback: ${callbackType}) => (unit => unit) = "${method.name}"`);
  return lines;
}

function buildConstraintNote(method: Method): string {
  const notes: string[] = [];
  for (const p of method.params) {
    const c = extractConstraints(p.type);
    if (c) notes.push(`${p.name}: ${formatConstraintNote(c)}`);
  }
  if (method.result) {
    const c = extractConstraints(method.result);
    if (c) notes.push(`result: ${formatConstraintNote(c)}`);
  }
  return notes.length ? `Constraints — ${notes.join(" | ")}` : "";
}

function paramToRes(p: Param): string {
  if (p.type.kind === "optional") {
    return `~${p.name}: option<${typeRefToRes((p.type as OptionalRef).inner)}>=?`;
  }
  return `~${p.name}: ${typeRefToRes(p.type)}`;
}

// ---------------------------------------------------------------------------
// TypeRef → ReScript string
// ---------------------------------------------------------------------------

function typeRefToRes(ref: TypeRef): string {
  switch (ref.kind) {
    case "primitive":
      return primitiveToRes(ref as PrimitiveRef);
    case "named": {
      const nr = ref as NamedRef;
      // ReScript uses lowercase first char for types
      const typeName = lcFirst(nr.name);
      return nr.module ? `${lcFirst(nr.module)}_${typeName}` : typeName;
    }
    case "array":
      return `array<${typeRefToRes((ref as ArrayRef).items)}>`;
    case "optional":
      return `option<${typeRefToRes((ref as OptionalRef).inner)}>`;
  }
}

function primitiveToRes(ref: PrimitiveRef): string {
  switch (ref.primitive) {
    case "bool":
      return "bool";
    case "string":
      return "string";
    case "unsigned":
    case "double":
      return "float";
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function lcFirst(s: string): string {
  return s.length === 0 ? s : s.charAt(0).toLowerCase() + s.slice(1);
}

// ---------------------------------------------------------------------------
// Register
// ---------------------------------------------------------------------------

registerGenerator("res", generate, "web");
