/**
 * TypeScript `.d.ts` generator.
 *
 * Conventions (from generator-conventions.md):
 *   - EnumType → string literal union: type AgePolicy = "app:adult" | ...
 *   - ObjectType → interface
 *   - Method(call) → function inside `declare namespace`, returns Promise<T>
 *   - Method(subscribe) → callback + () => void unsubscribe pattern
 *   - Optional params → param?: T
 *   - Output: out/ts/<Module>.d.ts
 */

import {
  ArrayRef,
  EnumTypeDecl,
  Method,
  Module,
  NamedRef,
  ObjectTypeDecl,
  OptionalRef,
  Param,
  PrimitiveRef,
  TypeDecl,
  TypeRef,
} from "../ast/types";
import { GenConfig, GeneratorOutput, extractConstraints, formatConstraintNote, registerGenerator } from "./index";

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

function generate(module: Module, _config: GenConfig): GeneratorOutput[] {
  const lines: string[] = [];

  lines.push(`// Auto-generated by firebolt-gen — do not edit manually.`);
  lines.push(`// Module: ${module.name}`);
  lines.push(``);

  // Emit type declarations
  for (const decl of module.types) {
    lines.push(...emitTypeDecl(decl));
    lines.push(``);
  }

  // Emit methods in a declare namespace
  lines.push(`declare namespace ${module.name} {`);
  for (const method of module.methods) {
    lines.push(...emitMethod(method).map((l) => `  ${l}`));
    lines.push(``);
  }
  lines.push(`}`);
  lines.push(``);

  return [
    {
      filePath: `ts/${module.name}.d.ts`,
      content: lines.join("\n"),
    },
  ];
}

// ---------------------------------------------------------------------------
// Type declarations
// ---------------------------------------------------------------------------

function emitTypeDecl(decl: TypeDecl): string[] {
  if (decl.kind === "enum") {
    return emitEnum(decl);
  }
  if (decl.kind === "object") {
    return emitObject(decl);
  }
  // union, array-alias, scalar-alias not needed for PoC
  return [`// [unsupported TypeDecl kind: ${(decl as TypeDecl).kind}]`];
}

function emitEnum(decl: EnumTypeDecl): string[] {
  const literals = decl.values.map((v) => `"${v.serializedId}"`).join(" | ");
  const lines: string[] = [];
  if (decl.description) {
    lines.push(`/** ${decl.description} */`);
  }
  lines.push(`type ${decl.name} = ${literals};`);
  return lines;
}

function emitObject(decl: ObjectTypeDecl): string[] {
  const lines: string[] = [];
  if (decl.description) {
    lines.push(`/** ${decl.description} */`);
  }
  lines.push(`interface ${decl.name} {`);
  for (const prop of decl.properties) {
    const opt = !prop.required ? "?" : "";
    const ref =
      !prop.required && prop.type.kind === "optional"
        ? (prop.type as OptionalRef).inner
        : prop.type;
    const inner = typeRefToTS(ref);
    const c = extractConstraints(ref);
    if (c) lines.push(`  /** Constraints: ${formatConstraintNote(c)} */`);
    lines.push(`  ${prop.name}${opt}: ${inner};`);
  }
  lines.push(`}`);
  return lines;
}

// ---------------------------------------------------------------------------
// Methods
// ---------------------------------------------------------------------------

function emitMethod(method: Method): string[] {
  if (method.kind === "call") {
    return emitCallMethod(method);
  }
  return emitSubscribeMethod(method);
}

function emitCallMethod(method: Method): string[] {
  const paramStr = method.params.map(paramToTS).join(", ");
  const resultType =
    method.result === null ? "void" : typeRefToTS(method.result);
  const constraintLines = collectConstraintLines(method);
  const doc = constraintLines.length
    ? `/** ${method.description}\n   * Constraints: ${constraintLines.join(" | ")} */`
    : `/** ${method.description} */`;
  return [
    doc,
    `function ${method.name}(${paramStr}): Promise<${resultType}>;`,
  ];
}

function emitSubscribeMethod(method: Method): string[] {
  const callbackType =
    method.result === null ? "() => void" : `(event: ${typeRefToTS(method.result)}) => void`;
  const paramStr = method.params.map(paramToTS).join(", ");
  const sep = paramStr ? ", " : "";
  const constraintLines = collectConstraintLines(method);
  const doc = constraintLines.length
    ? `/** ${method.description}\n   * Constraints — event payload: ${constraintLines.join(" | ")} */`
    : `/** ${method.description} */`;
  return [
    doc,
    `function ${method.name}(${paramStr}${sep}callback: ${callbackType}): () => void;`,
  ];
}

/** Collect constraint notes for all params + result of a method. */
function collectConstraintLines(method: Method): string[] {
  const notes: string[] = [];
  for (const p of method.params) {
    const c = extractConstraints(p.type);
    if (c) notes.push(`${p.name}: ${formatConstraintNote(c)}`);
  }
  if (method.result) {
    const c = extractConstraints(method.result);
    if (c) notes.push(formatConstraintNote(c));
  }
  return notes;
}

function paramToTS(p: Param): string {
  if (p.type.kind === "optional") {
    return `${p.name}?: ${typeRefToTS((p.type as OptionalRef).inner)}`;
  }
  return `${p.name}: ${typeRefToTS(p.type)}`;
}

// ---------------------------------------------------------------------------
// TypeRef → TypeScript string
// ---------------------------------------------------------------------------

function typeRefToTS(ref: TypeRef): string {
  switch (ref.kind) {
    case "primitive":
      return primitiveToTS(ref as PrimitiveRef);
    case "named": {
      const nr = ref as NamedRef;
      return nr.module ? `${nr.module}.${nr.name}` : nr.name;
    }
    case "array":
      return `${typeRefToTS((ref as ArrayRef).items)}[]`;
    case "optional":
      return `${typeRefToTS((ref as OptionalRef).inner)} | undefined`;
  }
}

function primitiveToTS(ref: PrimitiveRef): string {
  switch (ref.primitive) {
    case "bool":
      return "boolean";
    case "string":
      return "string";
    case "unsigned":
    case "double":
      return "number";
  }
}

// ---------------------------------------------------------------------------
// Register
// ---------------------------------------------------------------------------

registerGenerator("ts", generate, "web");
